# Generated by Django 2.2 on 2019-12-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('bprice', models.FloatField()),
                ('pinfo', models.CharField(max_length=100)),
                ('pimage', models.ImageField(upload_to='product_images/')),
                ('pstatus', models.CharField(max_length=10)),
                ('uinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel')),
            ],
        ),
    ]
